{{- if .Values.config.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hermes.fullname" . }}
  labels:
    {{- include "hermes.labels" . | nindent 4 }}
  {{- with .Values.config.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.config.data }}
data:
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
