{{- if and .Values.gateway.enabled .Values.gateway.persistence.enabled (not .Values.gateway.persistence.existingClaim) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "hermes.fullname" . }}-gateway
  labels:
    {{- include "hermes.componentLabels" (merge (deepCopy .) (dict "component" "gateway")) | nindent 4 }}
  annotations:
    {{- toYaml (merge (dict "helm.sh/resource-policy" "keep") (default (dict) .Values.gateway.persistence.annotations)) | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.gateway.persistence.accessMode }}
  {{- if .Values.gateway.persistence.storageClass }}
  storageClassName: {{ .Values.gateway.persistence.storageClass }}
  {{- end }}
  {{- with .Values.gateway.persistence.selector }}
  selector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.gateway.persistence.size }}
{{- end }}
