{{- if .Values.secret.enabled }}
---
apiVersion: v1
kind: Secret
type: {{ .Values.secret.type }}
metadata:
  name: {{ include "hermes.fullname" . }}
  labels:
    {{- include "hermes.labels" . | nindent 4 }}
  {{- with .Values.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  {{- with .Values.secret.data }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
stringData:
  {{- with .Values.secret.stringData }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
