{{- if .Values.gateway.enabled }}
{{- if (include "hermes.serviceAccountCreate" . | eq "true") }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hermes.serviceAccountName" . }}
  labels:
    {{- include "hermes.componentLabels" (merge (deepCopy .) (dict "component" "gateway")) | nindent 4 }}
  {{- with (include "hermes.serviceAccountAnnotations" . | fromYaml) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
